### ISSUE TITLE
Update Documentation to support DevOpsAPI update

### ISSUE THREAD

**Issue by acekevin** [CharlieHealth/jellyfish-devops-action#29]
This is just a suggestion to update README.md to match deprecation warnings from Jellyfish DevOps API. They will be updating to require that repo_name matches a format of `org-slug/repo-slug`. 

I think this can be fixed with just an update to README.md 

```
// repoName: ${{ github.event.repository.name }}
repoName: ${{ github.event.repository.full_name }}
```

Also, thanks for creating this action!

**Comment by aaronfullerton** [comment]
Thanks for the heads up! Updated the docs in #35
